# Generated by Django 4.1.13 on 2026-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoGenero',
            fields=[
                ('gen_cve', models.CharField(db_column='GEN_CVE', max_length=1, primary_key=True, serialize=False)),
                ('gen_descripcion', models.CharField(db_column='GEN_DESCRIPCION', max_length=20)),
            ],
            options={
                'db_table': 'CAT_GENERO',
                'ordering': ['gen_cve'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoMoneda',
            fields=[
                ('mon_cve', models.CharField(db_column='MON_CVE', max_length=6, primary_key=True, serialize=False)),
                ('mon_descripcion', models.CharField(db_column='MON_DESCRIPCION', max_length=150)),
            ],
            options={
                'db_table': 'CAT_MONEDAS',
                'ordering': ['mon_cve'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoDocto',
            fields=[
                ('descripdocto', models.CharField(db_column='DESCRIPDOCTO', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CAT_TIPODOCTO',
                'ordering': ['descripdocto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoFalta',
            fields=[
                ('fal_clave', models.CharField(db_column='FAL_CLAVE', max_length=4, primary_key=True, serialize=False)),
                ('fal_descripcion', models.CharField(db_column='FAL_DESCRIPCION', max_length=150)),
            ],
            options={
                'db_table': 'CAT_TFALTA',
                'ordering': ['fal_clave'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoSancion',
            fields=[
                ('clave', models.CharField(db_column='CLAVE', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=100)),
            ],
            options={
                'db_table': 'TIPOSANCION',
                'ordering': ['clave'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('clave', models.CharField(db_column='CLAVE', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=110)),
                ('tipo', models.IntegerField(db_column='TIPO')),
                ('dep_siglas', models.CharField(blank=True, db_column='DEP_SIGLAS', max_length=50, null=True)),
                ('dep_habilitado', models.CharField(blank=True, db_column='DEP_HABILITADO', max_length=1, null=True)),
                ('dep_idanterior', models.CharField(blank=True, db_column='DEP_IDANTERIOR', max_length=6, null=True)),
                ('dep_cvefinanzas', models.CharField(blank=True, db_column='DEP_CVEFINANZAS', max_length=6, null=True)),
                ('mostrarseesa', models.CharField(blank=True, db_column='MOSTRARSESEA', max_length=2, null=True)),
            ],
            options={
                'db_table': 'DEPENDENCIAS',
                'ordering': ['tipo', 'descripcion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inhabilitado',
            fields=[
                ('anio', models.CharField(db_column='AÑO', max_length=4, primary_key=True, serialize=False)),
                ('sancionid', models.CharField(db_column='SANCIONID', max_length=6)),
                ('oficio', models.CharField(blank=True, db_column='OFICIO', max_length=40, null=True)),
                ('f_oficio', models.DateField(blank=True, db_column='F_OFICIO', null=True)),
                ('expediente', models.CharField(blank=True, db_column='EXPEDIENTE', max_length=30, null=True)),
                ('f_resolucion', models.DateField(blank=True, db_column='F_RESOLUCION', null=True)),
                ('apaterno', models.CharField(blank=True, db_column='APATERNO', max_length=20, null=True)),
                ('amaterno', models.CharField(blank=True, db_column='AMATERNO', max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, db_column='NOMBRES', max_length=50, null=True)),
                ('dependencia', models.CharField(blank=True, db_column='DEPENDENCIA', max_length=3, null=True)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=100, null=True)),
                ('entidad_labora', models.CharField(blank=True, db_column='ENTIDAD_LABORA', max_length=80, null=True)),
                ('tiposancion', models.CharField(blank=True, db_column='TIPOSANCION', max_length=2, null=True)),
                ('tiposancion2', models.CharField(blank=True, db_column='TIPOSANCION2', max_length=2, null=True)),
                ('periodo', models.CharField(blank=True, db_column='PERIODO', max_length=20, null=True)),
                ('deinhabil', models.DateField(blank=True, db_column='DEINHABIL', null=True)),
                ('ainhabil', models.DateField(blank=True, db_column='AINHABIL', null=True)),
                ('motivo', models.CharField(blank=True, db_column='MOTIVO', max_length=300, null=True)),
                ('statussanc1', models.CharField(blank=True, db_column='STATUSSANC1', max_length=1, null=True)),
                ('statussanc2', models.CharField(blank=True, db_column='STATUSSANC2', max_length=1, null=True)),
                ('rfc', models.CharField(blank=True, db_column='RFC', max_length=13, null=True)),
                ('fejec1', models.DateField(blank=True, db_column='FEJEC1', null=True)),
                ('fejec2', models.DateField(blank=True, db_column='FEJEC2', null=True)),
                ('monto1', models.CharField(blank=True, db_column='MONTO1', max_length=30, null=True)),
                ('monto2', models.CharField(blank=True, db_column='MONTO2', max_length=30, null=True)),
                ('curp', models.CharField(blank=True, db_column='CURP', max_length=18, null=True)),
                ('fechareg', models.DateTimeField(blank=True, db_column='FECHAREG', null=True)),
                ('genero', models.CharField(blank=True, db_column='GENERO', max_length=1, null=True)),
                ('idsesea', models.DecimalField(blank=True, db_column='IDSESEA', decimal_places=0, max_digits=38, null=True)),
                ('cve_entidad_labora', models.CharField(blank=True, db_column='CVE_ENTIDAD_LABORA', max_length=6, null=True)),
                ('tipofalta', models.CharField(blank=True, db_column='TIPOFALTA', max_length=4, null=True)),
                ('nivelcateg', models.CharField(blank=True, db_column='NIVELCATEG', max_length=10, null=True)),
                ('resolucionurl', models.CharField(blank=True, db_column='RESOLUCIONURL', max_length=300, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='OBSERVACIONES', max_length=500, null=True)),
                ('cve_moneda1', models.CharField(blank=True, db_column='CVE_MONEDA1', max_length=6, null=True)),
                ('cve_moneda2', models.CharField(blank=True, db_column='CVE_MONEDA2', max_length=6, null=True)),
                ('tipo_docto', models.CharField(blank=True, db_column='TIPO_DOCTO', max_length=25, null=True)),
                ('titulo_docto', models.CharField(blank=True, db_column='TITULO_DOCTO', max_length=50, null=True)),
                ('descripcion_docto', models.CharField(blank=True, db_column='DESCRIPCION_DOCTO', max_length=50, null=True)),
                ('fecha_docto', models.DateField(blank=True, db_column='FECHA_DOCTO', null=True)),
                ('particular', models.CharField(blank=True, db_column='PARTICULAR', max_length=1, null=True)),
                ('montoapi1', models.DecimalField(blank=True, db_column='MONTOAPI1', decimal_places=0, max_digits=38, null=True)),
                ('montoapi2', models.DecimalField(blank=True, db_column='MONTOAPI2', decimal_places=0, max_digits=38, null=True)),
                ('gravedad', models.CharField(blank=True, db_column='GRAVEDAD', max_length=1, null=True)),
            ],
            options={
                'db_table': 'INHABILITADOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhabilitadoFederal',
            fields=[
                ('dependencia', models.CharField(blank=True, db_column='DEPENDENCIA', max_length=500, null=True)),
                ('rfc', models.CharField(db_column='RFC', max_length=10, primary_key=True, serialize=False)),
                ('homoclave', models.CharField(blank=True, db_column='HOMOCLAVE', max_length=3, null=True)),
                ('apaterno', models.CharField(blank=True, db_column='APATERNO', max_length=300, null=True)),
                ('amaterno', models.CharField(blank=True, db_column='AMATERNO', max_length=300, null=True)),
                ('nombres', models.CharField(blank=True, db_column='NOMBRES', max_length=300, null=True)),
                ('autsanc', models.CharField(blank=True, db_column='AUTSANC', max_length=500, null=True)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=500, null=True)),
                ('periodo', models.CharField(blank=True, db_column='PERIODO', max_length=300, null=True)),
                ('fechares', models.DateField(blank=True, db_column='FECHARES', null=True)),
                ('fechanot', models.DateField(blank=True, db_column='FECHANOT', null=True)),
                ('deinhabil', models.DateField(blank=True, db_column='DEINHABIL', null=True)),
                ('ainhabil', models.DateField(blank=True, db_column='AINHABIL', null=True)),
                ('fechainf', models.DateField(blank=True, db_column='FECHAINF', null=True)),
            ],
            options={
                'db_table': 'INHABILIFEDERAL',
                'managed': False,
            },
        ),
    ]
